### ISSUE TITLE
telegram-desktop

### ISSUE THREAD

**Issue by veloute** [rusty-snake/fireurl#7]
the line 
`dbus-user filter`

in the [telegram profile](https://github.com/netblue30/firejail/blob/master/etc/profile-m-z/telegram.profile) seems to cause fireurl to not work correctly for me.

**Comment by rusty-snake** [comment]
> seems to

Can you provide some more detailed STR and debugging.

Also, are you sure that telegram-desktop uses fireurl? Or did you just saw url open working / not working.

**Comment by veloute** [comment]
my bad. it appears that the issue has nothing to do with fireurl.
